import { createRemultServer } from "remult/server";
import { ChartData } from "./shared/ChartData";
import { Users } from "./shared/Users";

export const api = createRemultServer({
  entities: [ChartData, Users],
  initApi: async (remult) => {
    const usersRepo = remult.repo(Users);
    if ((await usersRepo.count()) === 0) {
      await usersRepo.insert([
        {
          key: "1",
          name: "Farand Danbury",
          age: 81,
          address: "346 Northport Alley",
          tags: ["nice"],
        },
        {
          key: "2",
          name: "Jessi Kellick",
          age: 17,
          address: "6 Scoville Pass",
          tags: ["lazy"],
        },
        {
          key: "3",
          name: "Isadora Scogin",
          age: 84,
          address: "2754 Briar Crest Circle",
          tags: ["cool"],
        },
        {
          key: "4",
          name: "Ermanno Luxmoore",
          age: 26,
          address: "3 American Ash Plaza",
          tags: ["developer"],
        },
        {
          key: "5",
          name: "Del Olechnowicz",
          age: 24,
          address: "998 American Center",
          tags: ["developer"],
        },
        {
          key: "6",
          name: "Katrinka Toomey",
          age: 19,
          address: "3873 Helena Point",
          tags: ["loser"],
        },
        {
          key: "7",
          name: "Pancho Darmody",
          age: 69,
          address: "0931 Novick Terrace",
          tags: ["developer"],
        },
        {
          key: "8",
          name: "Clare Stallion",
          age: 78,
          address: "75 Susan Street",
          tags: ["developer"],
        },
        {
          key: "9",
          name: "Brett De Hooge",
          age: 23,
          address: "6038 Thackeray Parkway",
          tags: ["loser"],
        },
        {
          key: "10",
          name: "Rainer Bembrigg",
          age: 88,
          address: "5 Dovetail Alley",
          tags: ["nice"],
        },
        {
          key: "11",
          name: "Felipe Fulks",
          age: 68,
          address: "75570 Express Road",
          tags: ["loser"],
        },
        {
          key: "12",
          name: "Elita Durkin",
          age: 18,
          address: "815 Maple Wood Center",
          tags: ["genius"],
        },
        {
          key: "13",
          name: "Winifred Tander",
          age: 27,
          address: "74 Badeau Circle",
          tags: ["developer"],
        },
        {
          key: "14",
          name: "Gerrilee Cockin",
          age: 82,
          address: "3762 Lerdahl Parkway",
          tags: ["developer"],
        },
        {
          key: "15",
          name: "Rene Meates",
          age: 71,
          address: "6150 Tomscot Road",
          tags: ["loser"],
        },
        {
          key: "16",
          name: "Beatrice Mathers",
          age: 31,
          address: "48132 Commercial Street",
          tags: ["genius"],
        },
        {
          key: "17",
          name: "Emmeline Dolling",
          age: 84,
          address: "4 Hooker Alley",
          tags: ["lazy"],
        },
        {
          key: "18",
          name: "Silvan Huggins",
          age: 90,
          address: "46665 Kings Way",
          tags: ["nice"],
        },
        {
          key: "19",
          name: "Marion Budnik",
          age: 90,
          address: "62076 Express Street",
          tags: ["developer"],
        },
        {
          key: "20",
          name: "Melisa Woodthorpe",
          age: 48,
          address: "745 Sunnyside Avenue",
          tags: ["nice"],
        },
        {
          key: "21",
          name: "Angelo Giacomuzzi",
          age: 63,
          address: "93822 Michigan Street",
          tags: ["lazy"],
        },
        {
          key: "22",
          name: "Noby Grove",
          age: 56,
          address: "471 Upham Street",
          tags: ["nice"],
        },
        {
          key: "23",
          name: "Aubree Tocher",
          age: 20,
          address: "37 Katie Pass",
          tags: ["loser"],
        },
        {
          key: "24",
          name: "Hercule Everil",
          age: 70,
          address: "7 Comanche Terrace",
          tags: ["developer"],
        },
        {
          key: "25",
          name: "Mechelle Gornall",
          age: 27,
          address: "452 Everett Avenue",
          tags: ["cool"],
        },
        {
          key: "26",
          name: "Amelita Knighton",
          age: 96,
          address: "45421 Maywood Park",
          tags: ["genius"],
        },
        {
          key: "27",
          name: "Wini Crickmoor",
          age: 68,
          address: "7886 Hoepker Parkway",
          tags: ["loser"],
        },
        {
          key: "28",
          name: "Jehanna Churchard",
          age: 24,
          address: "03 Almo Alley",
          tags: ["genius"],
        },
        {
          key: "29",
          name: "Maddy D'Ambrosi",
          age: 30,
          address: "8 Knutson Place",
          tags: ["loser"],
        },
        {
          key: "30",
          name: "Howie Boyet",
          age: 98,
          address: "19 American Ash Way",
          tags: ["nice"],
        },
        {
          key: "31",
          name: "Morty Obal",
          age: 22,
          address: "87567 Nevada Junction",
          tags: ["lazy"],
        },
        {
          key: "32",
          name: "Geoff Shurrocks",
          age: 58,
          address: "51669 Granby Way",
          tags: ["lazy"],
        },
        {
          key: "33",
          name: "Rowen Kordes",
          age: 21,
          address: "5 Jana Court",
          tags: ["lazy"],
        },
        {
          key: "34",
          name: "Shannen Whitty",
          age: 69,
          address: "70 Hoard Terrace",
          tags: ["genius"],
        },
        {
          key: "35",
          name: "Jacquelyn Sprigging",
          age: 53,
          address: "6468 Del Sol Plaza",
          tags: ["developer"],
        },
        {
          key: "36",
          name: "Sebastien Wilsdon",
          age: 96,
          address: "339 Hansons Point",
          tags: ["loser"],
        },
        {
          key: "37",
          name: "Harmonie Aharoni",
          age: 32,
          address: "5618 Pankratz Court",
          tags: ["genius"],
        },
        {
          key: "38",
          name: "Coop Carayol",
          age: 74,
          address: "1059 Caliangt Crossing",
          tags: ["developer"],
        },
        {
          key: "39",
          name: "Rudolfo Tamblingson",
          age: 56,
          address: "3292 Pearson Crossing",
          tags: ["genius"],
        },
        {
          key: "40",
          name: "Beau Baudain",
          age: 92,
          address: "63 Tennyson Junction",
          tags: ["developer"],
        },
        {
          key: "41",
          name: "Louis Sauvain",
          age: 22,
          address: "7 Drewry Road",
          tags: ["cool"],
        },
        {
          key: "42",
          name: "Garvy Hunt",
          age: 36,
          address: "69579 Lighthouse Bay Lane",
          tags: ["genius"],
        },
        {
          key: "43",
          name: "Deni Karet",
          age: 39,
          address: "7 Pankratz Point",
          tags: ["cool"],
        },
        {
          key: "44",
          name: "Dewain Bonner",
          age: 44,
          address: "64797 Arapahoe Junction",
          tags: ["developer"],
        },
        {
          key: "45",
          name: "Saundra Tunnick",
          age: 37,
          address: "11 Montana Hill",
          tags: ["genius"],
        },
        {
          key: "46",
          name: "Nata Zimmermanns",
          age: 80,
          address: "10 Lukken Alley",
          tags: ["developer"],
        },
        {
          key: "47",
          name: "Bennett Elener",
          age: 95,
          address: "8617 Morrow Street",
          tags: ["developer"],
        },
        {
          key: "48",
          name: "Linette Spriggs",
          age: 27,
          address: "983 Marcy Place",
          tags: ["genius"],
        },
        {
          key: "49",
          name: "Cesaro MacIllrick",
          age: 99,
          address: "8906 Dunning Plaza",
          tags: ["nice"],
        },
        {
          key: "50",
          name: "Berny Ceely",
          age: 62,
          address: "7549 Union Junction",
          tags: ["genius"],
        },
        {
          key: "51",
          name: "Iormina Upton",
          age: 76,
          address: "059 Burning Wood Drive",
          tags: ["genius"],
        },
        {
          key: "52",
          name: "Ali Perschke",
          age: 75,
          address: "8864 Declaration Park",
          tags: ["loser"],
        },
        {
          key: "53",
          name: "Bennett Duce",
          age: 27,
          address: "5255 Golf Course Place",
          tags: ["loser"],
        },
        {
          key: "54",
          name: "Anni Infantino",
          age: 58,
          address: "3170 Oxford Park",
          tags: ["developer"],
        },
        {
          key: "55",
          name: "Therese Szapiro",
          age: 86,
          address: "3 Main Hill",
          tags: ["genius"],
        },
        {
          key: "56",
          name: "Elva Bonallack",
          age: 25,
          address: "01339 Esch Road",
          tags: ["genius"],
        },
        {
          key: "57",
          name: "Goldarina Guerin",
          age: 22,
          address: "398 Lillian Point",
          tags: ["loser"],
        },
        {
          key: "58",
          name: "Rania Gooder",
          age: 81,
          address: "804 Clove Road",
          tags: ["loser"],
        },
        {
          key: "59",
          name: "Jena Glastonbury",
          age: 90,
          address: "52884 Rutledge Plaza",
          tags: ["lazy"],
        },
        {
          key: "60",
          name: "Ardra Doodney",
          age: 31,
          address: "9875 Katie Plaza",
          tags: ["developer"],
        },
        {
          key: "61",
          name: "Tremaine Papa",
          age: 38,
          address: "50 Towne Parkway",
          tags: ["developer"],
        },
        {
          key: "62",
          name: "Eyde Featherstonhaugh",
          age: 37,
          address: "2190 Eagan Road",
          tags: ["cool"],
        },
        {
          key: "63",
          name: "Sande Busse",
          age: 58,
          address: "0612 Manufacturers Junction",
          tags: ["lazy"],
        },
        {
          key: "64",
          name: "Hadley Janowicz",
          age: 39,
          address: "7721 Cardinal Circle",
          tags: ["genius"],
        },
        {
          key: "65",
          name: "Hayes Bahike",
          age: 80,
          address: "39396 Carey Point",
          tags: ["nice"],
        },
        {
          key: "66",
          name: "Elsey Greatex",
          age: 60,
          address: "80966 Cardinal Road",
          tags: ["developer"],
        },
        {
          key: "67",
          name: "Giacopo Ossipenko",
          age: 65,
          address: "5 Mcguire Plaza",
          tags: ["cool"],
        },
        {
          key: "68",
          name: "Godwin Gurnett",
          age: 43,
          address: "7532 Dapin Circle",
          tags: ["cool"],
        },
        {
          key: "69",
          name: "Rabbi Graith",
          age: 53,
          address: "9 Erie Avenue",
          tags: ["genius"],
        },
        {
          key: "70",
          name: "Gratiana Huske",
          age: 44,
          address: "1834 Bayside Pass",
          tags: ["cool"],
        },
        {
          key: "71",
          name: "Lovell MacRirie",
          age: 46,
          address: "7481 Muir Place",
          tags: ["developer"],
        },
        {
          key: "72",
          name: "Gates MacAirt",
          age: 85,
          address: "10 Karstens Point",
          tags: ["lazy"],
        },
        {
          key: "73",
          name: "Max McGriele",
          age: 99,
          address: "148 Golf Lane",
          tags: ["lazy"],
        },
        {
          key: "74",
          name: "Rollin Joron",
          age: 77,
          address: "23303 Roth Avenue",
          tags: ["loser"],
        },
        {
          key: "75",
          name: "Walden Elmar",
          age: 63,
          address: "0719 Tennyson Point",
          tags: ["loser"],
        },
        {
          key: "76",
          name: "Demetrius Brummell",
          age: 49,
          address: "26 Dakota Trail",
          tags: ["nice"],
        },
        {
          key: "77",
          name: "Agneta Broke",
          age: 82,
          address: "68 Old Shore Road",
          tags: ["nice"],
        },
        {
          key: "78",
          name: "Eric Hudless",
          age: 84,
          address: "4529 Talisman Alley",
          tags: ["nice"],
        },
        {
          key: "79",
          name: "Mart McCracken",
          age: 93,
          address: "26 Sloan Court",
          tags: ["cool"],
        },
        {
          key: "80",
          name: "Nady Borham",
          age: 64,
          address: "3961 Delladonna Hill",
          tags: ["lazy"],
        },
        {
          key: "81",
          name: "Perkin Wyldes",
          age: 95,
          address: "4729 Morrow Lane",
          tags: ["cool"],
        },
        {
          key: "82",
          name: "Griffin Wagenen",
          age: 43,
          address: "857 Daystar Trail",
          tags: ["nice"],
        },
        {
          key: "83",
          name: "Marsha Dart",
          age: 67,
          address: "9 Bunker Hill Terrace",
          tags: ["lazy"],
        },
        {
          key: "84",
          name: "Pierre Veregan",
          age: 79,
          address: "5 Reinke Plaza",
          tags: ["lazy"],
        },
        {
          key: "85",
          name: "Marsha Bartholomaus",
          age: 90,
          address: "0042 Vera Center",
          tags: ["cool"],
        },
        {
          key: "86",
          name: "Estella Van Schafflaer",
          age: 55,
          address: "117 Esch Road",
          tags: ["cool"],
        },
        {
          key: "87",
          name: "Goldia Bellas",
          age: 39,
          address: "38 Monument Plaza",
          tags: ["developer"],
        },
        {
          key: "88",
          name: "Moss Noye",
          age: 67,
          address: "7613 Pierstorff Parkway",
          tags: ["genius"],
        },
        {
          key: "89",
          name: "Edythe McCarron",
          age: 47,
          address: "63 Eagle Crest Lane",
          tags: ["cool"],
        },
        {
          key: "90",
          name: "Nathanial Rasor",
          age: 59,
          address: "45 Clove Park",
          tags: ["developer"],
        },
        {
          key: "91",
          name: "Camellia Haville",
          age: 90,
          address: "77 Dawn Way",
          tags: ["lazy"],
        },
        {
          key: "92",
          name: "Aryn Montel",
          age: 68,
          address: "3 Londonderry Road",
          tags: ["genius"],
        },
        {
          key: "93",
          name: "Brodie Shetliff",
          age: 56,
          address: "03 Trailsway Crossing",
          tags: ["lazy"],
        },
        {
          key: "94",
          name: "Gonzales Souter",
          age: 37,
          address: "65 Banding Pass",
          tags: ["developer"],
        },
        {
          key: "95",
          name: "Bradford Paxforde",
          age: 88,
          address: "93488 Dennis Drive",
          tags: ["lazy"],
        },
        {
          key: "96",
          name: "Eduino Sharnock",
          age: 91,
          address: "1930 Esker Alley",
          tags: ["lazy"],
        },
        {
          key: "97",
          name: "Dino Brittan",
          age: 56,
          address: "4 Farwell Crossing",
          tags: ["loser"],
        },
        {
          key: "98",
          name: "Agnola Keith",
          age: 30,
          address: "5 Meadow Ridge Center",
          tags: ["loser"],
        },
        {
          key: "99",
          name: "Donnie Cone",
          age: 65,
          address: "22493 Lerdahl Park",
          tags: ["lazy"],
        },
        {
          key: "100",
          name: "Fernando Mardy",
          age: 32,
          address: "304 Prentice Road",
          tags: ["cool"],
        },
      ]);
    }
  },
});
